#!/bin/bash
function finish() {
  echo Killing server, pid = $(lsof -i:8080 -t)
  kill $(lsof -i:8080 -t)
}

env_settings=--dev
if [[ ${PRODUCTION} = true ]]; then
  env_settings=--prod
fi

node --harmony ./node_modules/sails/bin/sails lift ${env_settings} &
server_pid=$!
trap finish EXIT
npm test
ret_code=$?
exit ${ret_code}
