#!/bin/bash
# travis sets PORT=80 by default which doesn't work for us
# we need root privilegies - but we can't use sudo because
# of using container based infrastructure
# (sudo: false in .travis.yml)
export PORT=8080
function finish() {
  if [[ -z ${PORT} ]]; then
    PORT=8080
  fi
  echo Killing server, pid = $(lsof -i:${PORT} -t)
  kill $(lsof -i:${PORT} -t)
}

env_settings=--dev
if [[ ${PRODUCTION} = true ]]; then
  env_settings=--prod
fi

node --harmony ./node_modules/sails/bin/sails lift ${env_settings} &
server_pid=$!
trap finish EXIT
npm test
ret_code=$?
exit ${ret_code}
