#!/bin/bash
TOMCAT_LOG="tomcat7.log"
stdbuf -o0 mvn tomcat7:run > ${TOMCAT_LOG} 2>&1 &
tomcat_pid=$!
stdbuf -o0 tail -f ${TOMCAT_LOG} | while read LOGLINE
do
    echo ${LOGLINE};
    [[ "${LOGLINE}" == *"Starting ProtocolHandler"* ]] && pkill -P $$ tail
done
echo "Tomcat is up and running!"
mvn test
ret_code=$?
kill ${tomcat_pid}
exit ${ret_code}
