var codes = [

// 
// Ukraine regions geocoding
// 

	{code:"UA-05", values:["Vinnytskaya", "Вінницька"]},
	{code:"UA-07", values:["Volyn", "Волинська"]},
	{code:"UA-09", values:["Luhansk", "Луганська"]},
	{code:"UA-12", values:["Dnipropetrovsk", "Дніпропетровська"]},
	{code:"UA-14", values:["Donetsk", "Донецька"]},
	{code:"UA-18", values:["Zhytomyr", "Житомирська"]},
	{code:"UA-21", values:["Transcarpathian", "Закарпатська"]},
	{code:"UA-23", values:["Zaporizhzhya", "Запорізька"]},
	{code:"UA-26", values:["Ivano-Frankivsk", "Івано-Франківська"]},
	{code:"UA-30", values:["Kyiv", "Київ"]},
	{code:"UA-32", values:["Kiev", "Київська"]},
	{code:"UA-35", values:["Kirovohrad", "Кіровоградська"]},
	{code:"UA-40", values:["Sevastopol", "Севастополь"]},
	{code:"UA-43", values:["Crimea", "Автономна Республіка Крим", "АР Крим"]},
	{code:"UA-46", values:["Lviv", "Львівська"]},
	{code:"UA-48", values:["Mykolaiv", "Миколаївська"]},
	{code:"UA-51", values:["Odesa", "Одеська"]},
	{code:"UA-53", values:["Poltava", "Полтавська"]},
	{code:"UA-56", values:["Rivne", "Рівненська"]},
	{code:"UA-59", values:["Sumy", "Сумська"]},
	{code:"UA-61", values:["Ternopil", "Тернопільська"]},
	{code:"UA-63", values:["Kharkiv", "Харківська"]},
	{code:"UA-65", values:["Kherson", "Херсонська"]},
	{code:"UA-68", values:["Khmelnytskyi", "Хмельницька"]},
	{code:"UA-71", values:["Cherkasy", "Черкаська"]},
	{code:"UA-74", values:["Chernihiv", "Чернігівська"]},
	{code:"UA-77", values:["Chernivtsi", "Чернівецька"]},

//
// countries geo coding
//
  
	{code:"ABW", values: ["Aruba", "ABW"]},
	{code:"AFG", values: ["Afghanistan", "AFG"]},
	{code:"AGO", values: ["Angola", "AGO"]},
	{code:"ALB", values: ["Albania", "ALB"]},
	{code:"ARB", values: ["Arab World", "ARB"]},
	{code:"ARE", values: ["United Arab Emirates", "ARE"]},
	{code:"ARG", values: ["Argentina", "ARG"]},
	{code:"ARM", values: ["Armenia", "ARM"]},
	{code:"ATG", values: ["Antigua and Barbuda", "ATG"]},
	{code:"AUS", values: ["Australia", "AUS"]},
	{code:"AUT", values: ["Austria", "AUT"]},
	{code:"AZE", values: ["Azerbaijan", "AZE"]},
	{code:"BDI", values: ["Burundi", "BDI"]},
	{code:"BEL", values: ["Belgium", "BEL"]},
	{code:"BEN", values: ["Benin", "BEN"]},
	{code:"BFA", values: ["Burkina Faso", "BFA"]},
	{code:"BGD", values: ["Bangladesh", "BGD"]},
	{code:"BGR", values: ["Bulgaria", "BGR"]},
	{code:"BHR", values: ["Bahrain", "BHR"]},
	{code:"BHS", values: ["Bahamas  The", "BHS"]},
	{code:"BIH", values: ["Bosnia and Herzegovina", "BIH"]},
	{code:"BLR", values: ["Belarus", "BLR"]},
	{code:"BLZ", values: ["Belize", "BLZ"]},
	{code:"BMU", values: ["Bermuda", "BMU"]},
	{code:"BOL", values: ["Bolivia", "BOL"]},
	{code:"BRA", values: ["Brazil", "BRA"]},
	{code:"BRB", values: ["Barbados", "BRB"]},
	{code:"BRN", values: ["Brunei Darussalam", "BRN"]},
	{code:"BTN", values: ["Bhutan", "BTN"]},
	{code:"BWA", values: ["Botswana", "BWA"]},
	{code:"CAF", values: ["Central African Republic", "CAF"]},
	{code:"CAN", values: ["Canada", "CAN"]},
	{code:"CEB", values: ["Central Europe and the Baltics", "CEB"]},
	{code:"CHE", values: ["Switzerland", "CHE"]},
	{code:"CHL", values: ["Chile", "CHL"]},
	{code:"CHN", values: ["China", "CHN"]},
	{code:"CIV", values: ["Cote d'Ivoire", "CIV"]},
	{code:"CMR", values: ["Cameroon", "CMR"]},
	{code:"COG", values: ["Congo  Rep ",  "COG"]},
	{code:"COL", values: ["Colombia", "COL"]},
	{code:"COM", values: ["Comoros", "COM"]},
	{code:"CPV", values: ["Cabo Verde", "CPV"]},
	{code:"CRI", values: ["Costa Rica", "CRI"]},
	{code:"CSS", values: ["Caribbean small states", "CSS"]},
	{code:"CUB", values: ["Cuba", "CUB"]},
	{code:"CYP", values: ["Cyprus", "CYP"]},
	{code:"CZE", values: ["Czech Republic", "CZE"]},
	{code:"DEU", values: ["Germany", "DEU"]},
	{code:"DJI", values: ["Djibouti", "DJI"]},
	{code: "DMA", values: ["Dominica", "DMA"]},
	{code: "DNK", values: ["Denmark", "DNK"]},
	{code: "DOM", values: ["Dominican Republic", "DOM"]},
	{code: "DZA", values: ["Algeria", "DZA"]},
	{code: "EAP", values: ["East Asia & Pacific (developing only)", "EAP"]},
	{code: "EAS", values: ["East Asia & Pacific (all income levels)", "EAS"]},
	{code: "ECA", values: ["Europe & Central Asia (developing only)", "ECA"]},
	{code: "ECS", values: ["Europe & Central Asia (all income levels)", "ECS"]},
	{code: "ECU", values: ["Ecuador", "ECU"]},
	{code: "EGY", values: ["Egypt  Arab Rep", "EGY"]},
	{code: "EMU", values: ["Euro area", "EMU"]},
	{code: "ERI", values: ["Eritrea", "ERI"]},
	{code: "ESP", values: ["Spain", "ESP"]},
	{code: "EST", values: ["Estonia", "EST"]},
	{code: "ETH", values: ["Ethiopia", "ETH"]},
	{code: "EUU", values: ["European Union", "EUU"]},
	{code: "FCS", values: ["Fragile and conflict affected situations", "FCS"]},
	{code: "FIN", values: ["Finland", "FIN"]},
	{code: "FJI", values: ["Fiji", "FJI"]},
	{code: "FRA", values: ["France", "FRA"]},
	{code: "FSM", values: ["Micronesia Fed Sts", "FSM"]},
	{code: "GAB", values: ["Gabon", "GAB"]},
	{code: "GBR", values: ["United Kingdom", "GBR"]},
	{code: "GEO", values: ["Georgia", "GEO"]},
	{code: "GHA", values: ["Ghana", "GHA"]},
	{code: "GIN", values: ["Guinea", "GIN"]},
	{code: "GMB", values: ["Gambia  The", "GMB"]},
	{code: "GNB", values: ["Guinea-Bissau", "GNB"]},
	{code: "GNQ", values: ["Equatorial Guinea", "GNQ"]},
	{code: "GRC", values: ["Greece", "GRC"]},
	{code: "GRD", values: ["Grenada", "GRD"]},
	{code: "GTM", values: ["Guatemala", "GTM"]},
	{code: "GUY", values: ["Guyana", "GUY"]},
	{code: "HIC", values: ["High income", "HIC"]},
	{code: "HKG", values: ["Hong Kong SAR  China", "HKG"]},
	{code: "HND", values: ["Honduras", "HND"]},
	{code: "HPC", values: ["Heavily indebted poor countries (HIPC)", "HPC"]},
	{code: "HRV", values: ["Croatia", "HRV"]},
	{code: "HTI", values: ["Haiti", "HTI"]},
	{code: "HUN", values: ["Hungary", "HUN"]},
	{code: "IDN", values: ["Indonesia", "IDN"]},
	{code: "IND", values: ["India", "IND"]},
	{code: "IRL", values: ["Ireland", "IRL"]},
	{code: "IRN", values: ["Iran  Islamic Rep ",  "IRN"]},
	{code: "IRQ", values: ["Iraq", "IRQ"]},
	{code: "ISL", values: ["Iceland", "ISL"]},
	{code: "ISR", values: ["Israel", "ISR"]},
	{code: "ITA", values: ["Italy", "ITA"]},
	{code: "JAM", values: ["Jamaica", "JAM"]},
	{code: "JOR", values: ["Jordan", "JOR"]},
	{code: "JPN", values: ["Japan", "JPN"]},
	{code: "KAZ", values: ["Kazakhstan", "KAZ"]},
	{code: "KEN", values: ["Kenya", "KEN"]},
	{code: "KGZ", values: ["Kyrgyz Republic", "KGZ"]},
	{code: "KHM", values: ["Cambodia", "KHM"]},
	{code: "KIR", values: ["Kiribati", "KIR"]},
	{code: "KNA", values: ["St  Kitts and Nevis", "KNA"]},
	{code: "KOR", values: ["Korea  Rep ",  "KOR"]},
	{code: "KWT", values: ["Kuwait", "KWT"]},
	{code: "LAC", values: ["Latin America & Caribbean (developing only)", "LAC"]},
	{code: "LAO", values: ["Lao PDR", "LAO"]},
	{code: "LBN", values: ["Lebanon", "LBN"]},
	{code: "LBR", values: ["Liberia", "LBR"]},
	{code: "LBY", values: ["Libya", "LBY"]},
	{code: "LCA", values: ["St  Lucia", "LCA"]},
	{code: "LCN", values: ["Latin America & Caribbean (all income levels)", "LCN"]},
	{code: "LDC", values: ["Least developed countries: UN classification", "LDC"]},
	{code: "LIC", values: ["Low income", "LIC"]},
	{code: "LKA", values: ["Sri Lanka", "LKA"]},
	{code: "LMC", values: ["Lower middle income", "LMC"]},
	{code: "LMY", values: ["Low & middle income", "LMY"]},
	{code: "LSO", values: ["Lesotho", "LSO"]},
	{code: "LTU", values: ["Lithuania", "LTU"]},
	{code: "LUX", values: ["Luxembourg", "LUX"]},
	{code: "LVA", values: ["Latvia", "LVA"]},
	{code: "MAC", values: ["Macao SAR  China", "MAC"]},
	{code: "MAR", values: ["Morocco", "MAR"]},
	{code: "MCO", values: ["Monaco", "MCO"]},
	{code: "MDA", values: ["Moldova", "MDA"]},
	{code: "MDG", values: ["Madagascar", "MDG"]},
	{code: "MDV", values: ["Maldives", "MDV"]},
	{code: "MEA", values: ["Middle East & North Africa (all income levels)", "MEA"]},
	{code: "MEX", values: ["Mexico", "MEX"]},
	{code: "MHL", values: ["Marshall Islands", "MHL"]},
	{code: "MIC", values: ["Middle income", "MIC"]},
	{code: "MKD", values: ["Macedonia  FYR", "MKD"]},
	{code: "MLI", values: ["Mali", "MLI"]},
	{code: "MLT", values: ["Malta", "MLT"]},
	{code: "MNA", values: ["Middle East & North Africa (developing only)", "MNA"]},
	{code: "MNE", values: ["Montenegro", "MNE"]},
	{code: "MNG", values: ["Mongolia", "MNG"]},
	{code: "MOZ", values: ["Mozambique", "MOZ"]},
	{code: "MRT", values: ["Mauritania", "MRT"]},
	{code: "MUS", values: ["Mauritius", "MUS"]},
	{code: "MWI", values: ["Malawi", "MWI"]},
	{code: "MYS", values: ["Malaysia", "MYS"]},
	{code: "NAC", values: ["North America", "NAC"]},
	{code: "NAM", values: ["Namibia", "NAM"]},
	{code: "NER", values: ["Niger", "NER"]},
	{code: "NGA", values: ["Nigeria", "NGA"]},
	{code: "NIC", values: ["Nicaragua", "NIC"]},
	{code: "NLD", values: ["Netherlands", "NLD"]},
	{code: "NOC", values: ["High income: nonOECD", "NOC"]},
	{code: "NOR", values: ["Norway", "NOR"]},
	{code: "NPL", values: ["Nepal", "NPL"]},
	{code: "NZL", values: ["New Zealand", "NZL"]},
	{code: "OEC", values: ["High income: OECD", "OEC"]},
	{code: "OED", values: ["OECD members", "OED"]},
	{code: "OMN", values: ["Oman", "OMN"]},
	{code: "OSS", values: ["Other small states", "OSS"]},
	{code: "PAK", values: ["Pakistan", "PAK"]},
	{code: "PAN", values: ["Panama", "PAN"]},
	{code: "PER", values: ["Peru", "PER"]},
	{code: "PHL", values: ["Philippines", "PHL"]},
	{code: "PLW", values: ["Palau", "PLW"]},
	{code: "PNG", values: ["Papua New Guinea", "PNG"]},
	{code: "POL", values: ["Poland", "POL"]},
	{code: "PRI", values: ["Puerto Rico", "PRI"]},
	{code: "PRT", values: ["Portugal", "PRT"]},
	{code: "PRY", values: ["Paraguay", "PRY"]},
	{code: "PSS", values: ["Pacific island small states", "PSS"]},
	{code: "QAT", values: ["Qatar", "QAT"]},
	{code: "ROU", values: ["Romania", "ROU"]},
	{code: "RUS", values: ["Russian Federation", "RUS"]},
	{code: "RWA", values: ["Rwanda", "RWA"]},
	{code: "SAS", values: ["South Asia", "SAS"]},
	{code: "SAU", values: ["Saudi Arabia", "SAU"]},
	{code: "SDN", values: ["Sudan", "SDN"]},
	{code: "SEN", values: ["Senegal", "SEN"]},
	{code: "SGP", values: ["Singapore", "SGP"]},
	{code: "SLB", values: ["Solomon Islands", "SLB"]},
	{code: "SLE", values: ["Sierra Leone", "SLE"]},
	{code: "SLV", values: ["El Salvador", "SLV"]},
	{code: "SRB", values: ["Serbia", "SRB"]},
	{code: "SSA", values: ["Sub-Saharan Africa (developing only)", "SSA"]},
	{code: "SSD", values: ["South Sudan", "SSD"]},
	{code: "SSF", values: ["Sub-Saharan Africa (all income levels)", "SSF"]},
	{code: "SST", values: ["Small states", "SST"]},
	{code: "STP", values: ["Sao Tome and Principe", "STP"]},
	{code: "SUR", values: ["Suriname", "SUR"]},
	{code: "SVK", values: ["Slovak Republic", "SVK"]},
	{code: "SVN", values: ["Slovenia", "SVN"]},
	{code: "SWE", values: ["Sweden", "SWE"]},
	{code: "SWZ", values: ["Swaziland", "SWZ"]},
	{code: "SYC", values: ["Seychelles", "SYC"]},
	{code: "TCD", values: ["Chad", "TCD"]},
	{code: "TGO", values: ["Togo", "TGO"]},
	{code: "THA", values: ["Thailand", "THA"]},
	{code: "TJK", values: ["Tajikistan", "TJK"]},
	{code: "TKM", values: ["Turkmenistan", "TKM"]},
	{code: "TLS", values: ["Timor-Leste", "TLS"]},
	{code: "TON", values: ["Tonga", "TON"]},
	{code: "TTO", values: ["Trinidad and Tobago", "TTO"]},
	{code: "TUN", values: ["Tunisia", "TUN"]},
	{code: "TUR", values: ["Turkey", "TUR"]},
	{code: "TUV", values: ["Tuvalu", "TUV"]},
	{code: "TZA", values: ["Tanzania", "TZA"]},
	{code: "UGA", values: ["Uganda", "UGA"]},
	{code: "UKR", values: ["#UKR", "UKR"]},
	{code: "UMC", values: ["Upper middle income", "UMC"]},
	{code: "URY", values: ["Uruguay", "URY"]},
	{code: "USA", values: ["United States", "USA"]},
	{code: "UZB", values: ["Uzbekistan", "UZB"]},
	{code: "VCT", values: ["St  Vincent and the Grenadines", "VCT"]},
	{code: "VEN", values: ["Venezuela  RB", "VEN"]},
	{code: "VNM", values: ["Vietnam", "VNM"]},
	{code: "VUT", values: ["Vanuatu", "VUT"]},
	{code: "PSE", values: ["West Bank and Gaza", "PSE"]},
	{code: "WLD", values: ["World", "WLD"]},
	{code: "WSM", values: ["Samoa", "WSM"]},
	{code: "YEM", values: ["Yemen  Rep ",  "YEM"]},
	{code: "ZAF", values: ["South Africa", "ZAF"]},
	{code: "COD", values: ["Congo  Dem  Rep ",  "COD"]},
	{code: "ZMB", values: ["Zambia", "ZMB"]},
	{code: "ZWE", values: ["Zimbabwe", "ZWE	"]}



]


exports.getCode = function(value){
	var row = codes.filter(function(item){
		return item.values.filter(function(v){return v.toUpperCase() == value.toUpperCase()}).length > 0
	})
	
	if(row.length>0){
		return row[0].code;
	}
	
	return value;
}