{ html: 
   [ { lang: 'en',
       class: 'webkit chrome chrome51 win win7 js ltr orientation_landscape maxw_1280 non-retina js rgba' } ],
  head: [],
  meta: 
   [ { 'http-equiv': 'Content-Type',
       content: 'text/html; charset=UTF-8',
       innerHTML: '\n  ' },
     { 'http-equiv': 'X-UA-Compatible',
       content: 'IE=Edge,chrome=1',
       innerHTML: '\n  \n  ' },
     { name: 'viewport',
       content: 'width=device-width, initial-scale=1',
       innerHTML: '\n  ' },
     { content: 'authenticity_token',
       name: 'csrf-param',
       innerHTML: '\n' },
     { content: 'yQrEUftM3Xxftlge4kG1CICmQsjVjt07uYai7PqBMGQ=',
       name: 'csrf-token',
       innerHTML: '\n  ' } ],
  title: [ { innerHTML: 'Data Catalog API – World Bank Data Help Desk' } ],
  link: 
   [ { rel: 'P3Pv1',
       href: 'https://datahelpdesk.worldbank.org/w3c/p3p.xml',
       innerHTML: '\n\n    ' },
     { rel: 'canonical',
       href: 'https://datahelpdesk.worldbank.org/knowledgebase/articles/902049-data-catalog-api',
       innerHTML: '\n\n    ' },
     { href: './Data Catalog API – World Bank Data Help Desk_files/site2-459ac7cf35e91427372521845015ed6c.css',
       media: 'all',
       rel: 'stylesheet',
       innerHTML: '\n\n\n  ' },
     { href: '//assets0.uvcdn.com/pkg/clients/site2/ie-dd504534fd5adc0f02c51328941904bf.css',
       media: 'screen',
       rel: 'stylesheet',
       innerHTML: '\n  ' },
     { type: 'text/css',
       rel: 'stylesheet',
       media: 'all',
       href: './Data Catalog API – World Bank Data Help Desk_files/uv-style2.css',
       innerHTML: '\n' },
     { type: 'text/css',
       rel: 'stylesheet',
       media: 'all',
       href: './Data Catalog API – World Bank Data Help Desk_files/network.css',
       innerHTML: '\n\n\n      ' } ],
  script: 
   [ { type: 'application/javascript',
       async: ' defer=',
       '"src': './Data Catalog API – World Bank Data Help Desk_files/track.js' },
     { type: 'text/javascript',
       async: ' defer=',
       '"src': './Data Catalog API – World Bank Data Help Desk_files/saved_resource' },
     { type: 'text/javascript', async: ' src=' },
     { type: 'text/javascript', async: ' src=' },
     { type: 'text/javascript', async: ' src=' },
     { type: 'text/javascript' },
     { src: '//assets0.uvcdn.com/pkg/clients/site2/lt_IE_9-2c58c1ee1dbefb700ef2333ae314783d.js' },
     { type: 'text/javascript' },
     { src: './Data Catalog API – World Bank Data Help Desk_files/all.js',
       async: '' },
     { type: 'text/x-jquery-tmpl', id: 'uvSearch-template-articles' },
     { type: 'text/x-jquery-tmpl', id: 'uvSearch-template-ideas' },
     { type: 'text/x-jquery-tmpl', id: 'uvSearch-template-title' },
     { id: 'uv-user-panel', type: 'text/x-jquery-tmpl' },
     { type: 'text/javascript' },
     { id: 'portalForumsTmpl', type: 'text/x-jquery-tmpl' },
     { id: 'portalAltForumsTmpl', type: 'text/x-jquery-tmpl' },
     { id: 'sidebarForumsTmpl', type: 'text/x-jquery-tmpl' },
     { src: './Data Catalog API – World Bank Data Help Desk_files/site2-32c66ad3d67d461e59e57b585a06918e.js' },
     { type: 'text/javascript' },
     { src: './Data Catalog API – World Bank Data Help Desk_files/uv-scripts2.js',
       type: 'text/javascript' },
     { src: './Data Catalog API – World Bank Data Help Desk_files/WebStatsUtil.js',
       type: 'text/javascript' },
     { type: 'text/javascript' },
     { src: './Data Catalog API – World Bank Data Help Desk_files/s_code_remote.js',
       type: 'text/javascript' },
     { type: 'text/javascript' },
     { type: 'text/javascript' },
     { type: 'text/javascript' },
     { type: 'text/javascript' },
     { type: 'text/javascript' },
     { type: 'text/javascript' },
     { type: 'text/javascript' } ],
  style: 
   [ { type: 'text/css' },
     { type: 'text/css' },
     { type: 'text/css', media: 'screen' },
     { type: 'text/css' } ],
  body: 
   [ { class: 'uv-primaryColor-dark uv-locale-en uv-direction-ltr uv-topic uv-topic-125589 uv-no-user uv-helpdesk uv-article-page',
       innerHTML: '\n  ' } ],
  div: 
   [ { id: 'fb-root', class: ' fb_reset' },
     { style: 'position: absolute; top: -10000px; height: 0px; width: 0px;' },
     { style: 'position: absolute; top: -10000px; height: 0px; width: 0px;' },
     { class: 'uvPageContainer', innerHTML: '\n\n      ' },
     { id: 'wrapper', class: 'clear-block', innerHTML: '\n\n' },
     { id: 'wbg-header',
       class: 'clear-block',
       innerHTML: '\n\n\n            ' },
     { class: 'clear-block wbg-logo', innerHTML: '\n\t\t\t\t' },
     { class: 'global-search', innerHTML: '\n\t\t\t\t\t' },
     { class: 'global-language-selector',
       innerHTML: '\n                    ' },
     { class: 'clear-block global-nav',
       innerHTML: '\n                ' },
     { id: 'wbg-site-name', class: 'clear-block' },
     { id: 'local-nav', class: 'clear-block', innerHTML: '\n\n' },
     { class: 'local-nav-links clear-block', innerHTML: '\n\n' },
     { id: 'main-content',
       class: 'clear-block',
       innerHTML: '\n\n    \n\n\n\n' },
     { class: 'uvContainer uvBody', innerHTML: '\n  ' },
     { class: 'uvRow', innerHTML: '\n    ' },
     { class: 'uvCol-8', innerHTML: '\n      \n      ' },
     { class: 'uvBreadcrumbs', innerHTML: '\n              ' },
     { class: 'uvCol-4 uvSidebar uvCol-last', innerHTML: '\n      ' },
     { class: 'uvModule uvModule-session',
       'aria-live': 'polite',
       'aria-relevant': 'additions removals',
       innerHTML: '\n  ' },
     { class: 'uvSigninMode',
       style: 'display:none',
       innerHTML: 'prestine' },
     { class: 'uvField uvField-display_name uvField-first',
       innerHTML: '\n        ' },
     { class: 'uvField uvField-email uvField-first',
       innerHTML: '\n        ' },
     { class: 'uvFieldEtc uvFieldEtc-unprotected',
       innerHTML: 'Check!' },
     { class: 'uvFieldEtc uvFieldEtc-email_invalid',
       innerHTML: 'invalid email' },
     { class: 'uvFieldEtc uvFieldEtc-thinking',
       innerHTML: '(thinking…)' },
     { class: 'uvFieldEtc uvFieldEtc-reset', innerHTML: 'Reset' },
     { class: 'uvFieldEtc uvFieldEtc-providers',
       innerHTML: '\n            ' },
     { class: 'uvField uvField-authentication',
       innerHTML: '\n        ' },
     { class: 'password', innerHTML: '\n          ' },
     { class: 'uvFieldEtc uvFieldEtc-password_invalid' },
     { class: 'uvFieldEtc uvFieldEtc-forgot_password' },
     { class: 'uvFieldEtc uvFieldEtc-create_password' },
     { style: 'clear:both;' },
     { class: 'uvField uvField-tos_custom',
       innerHTML: '\n          ' },
     { class: 'uvField uvField-logged_in uvField-first',
       innerHTML: '\n    ' },
     { class: 'uvFormFlash uvFormFlash-error', innerHTML: '\n  ' },
     { class: 'uvFormFlashMessage' },
     { class: 'uvFormFlash uvFormFlash-info', innerHTML: '\n  ' },
     { class: 'uvFormFlashMessage' },
     { class: 'submit_region', innerHTML: '\n  ' },
     { class: 'uvModule uvModule-topSidebar', innerHTML: '\n    ' },
     { class: 'uvModule uvModule-helpdesk', innerHTML: '\n        ' },
     { class: 'uvModule uvModule-mainSidebar', innerHTML: '\n\n  ' },
     { class: 'uvField uvField-search', innerHTML: '\n        ' },
     { class: 'uvFieldEtc uvFieldEtc-thinking',
       innerHTML: '(thinking…)' },
     { id: 'uvSearch-results-articles',
       class: 'uvSearchResults uvSearchResults-articles' },
     { id: 'uvSearch-results-ideas',
       class: 'uvSearchResults uvSearchResults-ideas' },
     { id: 'wbg-footer', class: 'clear-block', innerHTML: '\n\n' },
     { class: 'footer-breadcrumb clear-block',
       innerHTML: '\n                ' },
     { class: 'ieClearFix' },
     { class: 'footer-fat clear-block',
       innerHTML: '\n                ' },
     { class: 'footer-links clear-block',
       innerHTML: '\n                    ' },
     { class: 'link-set-1 columns',
       innerHTML: '\n                        ' },
     { class: 'link-set-2 columns',
       innerHTML: '\n                        ' },
     { class: 'link-block first',
       innerHTML: '\n                                    ' },
     { class: 'link-block',
       innerHTML: '\n                                    ' },
     { class: 'link-block',
       innerHTML: '\n                                    ' },
     { class: 'link-block last',
       innerHTML: '\n                                    ' },
     { class: 'link-block first',
       innerHTML: '\n                                    ' },
     { class: 'link-block',
       innerHTML: '\n                                    ' },
     { class: 'link-block',
       innerHTML: '\n                                    ' },
     { class: 'link-block last',
       innerHTML: '\n                                    ' },
     { class: 'ieClearFix', innerHTML: '\n                    ' },
     { class: 'wbg-partners clear-block', innerHTML: '\n\t\t\t\t\t' },
     { class: 'worldbank-partner',
       innerHTML: '\n                        ' },
     { class: 'ieClearFix', innerHTML: '\n                    ' },
     { class: 'wbg-misc-links clear-block',
       innerHTML: '\n                    ' },
     { class: 'hotlineNumber',
       innerHTML: '\n                        ' },
     { class: 'ender' },
     { class: 'vcard', innerHTML: '\n        ' },
     { class: 'uvUserNav', innerHTML: '\n        ' },
     { class: 'uvListItemFooter', innerHTML: '${idea_count} ' },
     { class: 'uvPasswordReset-overlay',
       style: 'display: none',
       innerHTML: '\n  ' },
     { class: 'uvPasswordReset-dialog ', innerHTML: '\n    ' },
     { class: 'uvPasswordReset-dialog-header',
       innerHTML: '\n      ' },
     { class: 'uvPasswordReset-dialog-content typeset',
       innerHTML: '\n      ' },
     { class: 'uvPasswordReset-dialog-buttons',
       innerHTML: '\n        ' },
     { id: 'fancybox-tmp' },
     { id: 'fancybox-loading' },
     { id: 'fancybox-overlay' },
     { id: 'fancybox-wrap' },
     { id: 'fancybox-outer' },
     { class: 'fancybox-bg', id: 'fancybox-bg-n' },
     { class: 'fancybox-bg', id: 'fancybox-bg-ne' },
     { class: 'fancybox-bg', id: 'fancybox-bg-e' },
     { class: 'fancybox-bg', id: 'fancybox-bg-se' },
     { class: 'fancybox-bg', id: 'fancybox-bg-s' },
     { class: 'fancybox-bg', id: 'fancybox-bg-sw' },
     { class: 'fancybox-bg', id: 'fancybox-bg-w' },
     { class: 'fancybox-bg', id: 'fancybox-bg-nw' },
     { id: 'fancybox-content' },
     { id: 'fancybox-title' },
     { id: 'tiptip_holder', style: 'max-width:300px;' },
     { id: 'tiptip_arrow' },
     { id: 'tiptip_arrow_inner' },
     { id: 'tiptip_content' } ],
  iframe: 
   [ { name: 'fb_xdm_frame_https',
       frameborder: '0',
       allowtransparency: 'true',
       allowfullscreen: 'true',
       scrolling: 'no',
       id: 'fb_xdm_frame_https',
       'aria-hidden': 'true',
       title: 'Facebook Cross Domain Communication Frame',
       tabindex: '-1',
       src: './Data Catalog API – World Bank Data Help Desk_files/xd_arbiter.html',
       style: 'border: none;' },
     { name: 'f31ac6348854b3c',
       frameborder: '0',
       allowtransparency: 'true',
       allowfullscreen: 'true',
       scrolling: 'no',
       src: './Data Catalog API – World Bank Data Help Desk_files/ping.html',
       style: 'display: none;' } ],
  a: 
   [ { class: 'wbg-logo',
       title: 'The World Bank Working for a World Free of Poverty',
       href: 'http://www.worldbank.org/' },
     { href: 'http://www.worldbank.org/', innerHTML: 'English' },
     { href: 'http://www.bancomundial.org/', innerHTML: 'Español' },
     { href: 'http://www.banquemondiale.org/',
       innerHTML: 'Français' },
     { href: 'http://www.albankaldawli.org/', innerHTML: 'عربي' },
     { href: 'http://www.worldbank.org/eca/russian/',
       innerHTML: 'Русский' },
     { href: 'http://www.worldbank.org.cn/Chinese/',
       innerHTML: '中文' },
     { class: 'more',
       href: 'http://www.worldbank.org/languages',
       title: 'More Languages',
       innerHTML: '\n                        ' },
     { href: 'http://www.worldbank.org/', innerHTML: 'Home' },
     { href: 'http://www.worldbank.org/en/about',
       innerHTML: 'About' },
     { href: 'http://data.worldbank.org/', innerHTML: 'Data' },
     { href: 'http://econ.worldbank.org/WBSITE/EXTERNAL/EXTDEC/0,,menuPK:476823~pagePK:64165236~piPK:64165141~theSitePK:469372,00.html',
       innerHTML: '\n                        Research' },
     { href: 'http://wbi.worldbank.org/wbi/', innerHTML: 'Learning' },
     { href: 'http://www.worldbank.org/en/news', innerHTML: 'News' },
     { href: 'http://www.worldbank.org/projects?lang=en',
       innerHTML: 'Projects &amp; Operations' },
     { href: 'http://www.worldbank.org/reference/',
       innerHTML: 'Publications' },
     { href: 'http://www.worldbank.org/en/country',
       innerHTML: 'Countries' },
     { href: 'http://www.worldbank.org/en/topic',
       innerHTML: 'Topics' },
     { href: 'http://data.worldbank.org/', innerHTML: 'Data' },
     { href: 'http://data.worldbank.org/country',
       innerHTML: 'By Country' },
     { href: 'http://data.worldbank.org/topic',
       innerHTML: 'By Topic' },
     { href: 'http://data.worldbank.org/indicator',
       innerHTML: 'Indicators' },
     { href: 'http://data.worldbank.org/data-catalog',
       innerHTML: 'Data Catalog' },
     { href: 'http://microdata.worldbank.org',
       title: '',
       innerHTML: 'Microdata' },
     { href: 'http://blogs.worldbank.org/opendata',
       title: '',
       innerHTML: 'Blog' },
     { href: 'http://data.worldbank.org/news', innerHTML: 'News' },
     { href: 'http://data.worldbank.org/about',
       title: '',
       innerHTML: 'About' },
     { class: 'active',
       href: 'http://datahelpdesk.worldbank.org',
       innerHTML: 'Support' },
     { href: 'http://data.worldbank.org/products',
       innerHTML: 'Products' },
     { href: 'https://datahelpdesk.worldbank.org/knowledgebase/topics/125589-developer-information',
       innerHTML: '← Developer Information' },
     { href: 'http://data.worldbank.org/developers/data.worldbank.org/data-catalog',
       innerHTML: 'World Bank’s Open Data Catalog' },
     { href: 'http://data.worldbank.org/summary-terms-of-use',
       innerHTML: 'World Bank’s Terms of Use' },
     { class: 'uvAnonymousOnly uvStyle-link',
       href: 'https://datahelpdesk.worldbank.org/site/signin?lang=en',
       innerHTML: 'Flag this article as inaccurate…' },
     { href: 'https://datahelpdesk.worldbank.org/admin/faqs/902049',
       rel: 'nofollow',
       class: 'uvAdminOnly uvAdminOnly-inline',
       innerHTML: 'Admin →' },
     { href: 'https://datahelpdesk.worldbank.org/signin',
       innerHTML: 'sign in' },
     { href: 'https://graph.facebook.com/oauth/authorize?client_id=46468144668&amp;redirect_uri=https%3A%2F%2Fauth.uservoice.com%2Ffacebook%2F136660&amp;scope=email&amp;display=popup',
       tabindex: '0',
       title: 'Sign in via Facebook' },
     { href: 'https://auth.uservoice.com/google/136660',
       tabindex: '0',
       title: 'Sign in via Google' },
     { href: 'https://datahelpdesk.worldbank.org/users/forgot_password',
       class: 'uvFieldEtc-password_reset',
       innerHTML: 'Forgot password?' },
     { href: 'https://datahelpdesk.worldbank.org/users/forgot_password',
       class: 'uvFieldEtc-password_reset',
       innerHTML: 'Create a password' },
     { href: 'https://datahelpdesk.worldbank.org/tos',
       target: '_blank',
       rel: 'external',
       title: 'Opens in new window',
       innerHTML: 'terms of service' },
     { href: 'https://datahelpdesk.worldbank.org/logout',
       innerHTML: 'Sign out' },
     { class: 'uvFormFlashClose',
       href: 'https://datahelpdesk.worldbank.org/knowledgebase/articles/902049-data-catalog-api#close',
       innerHTML: 'Close' },
     { class: 'uvFormFlashClose',
       href: 'https://datahelpdesk.worldbank.org/knowledgebase/articles/902049-data-catalog-api#close',
       innerHTML: 'Close' },
     { href: 'http://go.worldbank.org/C09SUA7BK0',
       innerHTML: 'terms of use' },
     { class: 'devels',
       href: 'https://datahelpdesk.worldbank.org/knowledgebase/topics/125589',
       innerHTML: 'Developer Info' },
     { href: 'https://datahelpdesk.worldbank.org/knowledgebase/topics/125589-developer-information',
       innerHTML: 'Developer Information' },
     { href: 'https://datahelpdesk.worldbank.org/knowledgebase/articles/889386-developer-information-overview',
       innerHTML: 'Developer Information: Overview' },
     { href: 'https://datahelpdesk.worldbank.org/knowledgebase/articles/889392-api-documentation',
       innerHTML: 'API: Documentation' },
     { href: 'https://datahelpdesk.worldbank.org/knowledgebase/articles/898581-api-basic-call-structure',
       innerHTML: 'API: Basic Call Structure' },
     { href: 'https://datahelpdesk.worldbank.org/knowledgebase/articles/898587-api-catalog-source-queries',
       innerHTML: 'API: Catalog Source Queries' },
     { href: 'https://datahelpdesk.worldbank.org/knowledgebase/articles/898590-api-country-queries',
       innerHTML: 'API: Country Queries' },
     { href: 'https://datahelpdesk.worldbank.org/knowledgebase/articles/898596-api-income-level-queries',
       innerHTML: 'API: Income Level Queries' },
     { href: 'https://datahelpdesk.worldbank.org/knowledgebase/articles/898599-api-indicator-queries',
       innerHTML: 'API: Indicator Queries' },
     { href: 'https://datahelpdesk.worldbank.org/knowledgebase/articles/898608-api-lending-type-queries',
       innerHTML: 'API: Lending Type Queries' },
     { href: 'https://datahelpdesk.worldbank.org/knowledgebase/articles/898611-api-topic-queries',
       innerHTML: 'API: Topic Queries' },
     { href: 'https://datahelpdesk.worldbank.org/knowledgebase/articles/898614-api-aggregates-regions-and-income-levels',
       innerHTML: 'API: Aggregates - Regions and Income Levels' },
     { href: 'https://datahelpdesk.worldbank.org/knowledgebase/articles/898620-api-error-codes',
       innerHTML: 'API: Error Codes' },
     { href: 'https://datahelpdesk.worldbank.org/knowledgebase/articles/889461-api-sources',
       innerHTML: 'API: Sources' },
     { href: 'https://datahelpdesk.worldbank.org/knowledgebase/articles/902049-data-catalog-api',
       innerHTML: 'Data Catalog API' },
     { href: 'https://datahelpdesk.worldbank.org/knowledgebase/articles/902061-climate-data-api',
       innerHTML: 'Climate Data API' },
     { href: 'https://datahelpdesk.worldbank.org/knowledgebase/articles/902064-development-best-practices',
       innerHTML: 'Development Best Practices' },
     { href: 'https://datahelpdesk.worldbank.org/knowledgebase/articles/889464-wbopendata-stata-module-to-access-world-bank-data',
       innerHTML: 'wbopendata: Stata module to access World Bank databases' },
     { href: '${article.path}', innerHTML: '${article.question}' },
     { href: '/search?filter=articles&query=${response_data.query}',
       innerHTML: 'More articles &rarr;' },
     { href: '${idea.path}',
       innerHTML: '\n                    ${idea.title}\n                  ' },
     { href: '/search?filter=ideas&query=${response_data.query}',
       innerHTML: 'More ideas &rarr;' },
     { href: '/search?filter=merged&query=${query}',
       innerHTML: 'Search results' },
     { href: 'https://datahelpdesk.worldbank.org/knowledgebase/articles/902049-data-catalog-api',
       class: 'uvSearch-results-clear',
       innerHTML: 'Clear search results' },
     { class: 'uvLink-idea',
       href: 'https://datahelpdesk.worldbank.org/forums/162856-new-data',
       innerHTML: 'Give feedback' },
     { href: 'https://datahelpdesk.worldbank.org/forums/203367-general-suggestions',
       title: 'View all ideas in General Suggestions',
       innerHTML: 'General Suggestions' },
     { href: 'https://datahelpdesk.worldbank.org/forums/162856-new-data',
       title: 'View all ideas in New Data',
       innerHTML: 'New Data' },
     { href: 'https://datahelpdesk.worldbank.org/forums/170263-website-improvements',
       title: 'View all ideas in Website Improvements',
       innerHTML: 'Website Improvements' },
     { class: 'uvLink-knowledgebase',
       href: 'https://datahelpdesk.worldbank.org/knowledgebase',
       innerHTML: 'Knowledge Base' },
     { href: 'https://datahelpdesk.worldbank.org/knowledgebase/topics/19280-country-classification',
       title: 'View all articles in Country Classification',
       innerHTML: 'Country Classification' },
     { href: 'https://datahelpdesk.worldbank.org/knowledgebase/topics/19371-currencies',
       title: 'View all articles in Currencies',
       innerHTML: 'Currencies' },
     { href: 'https://datahelpdesk.worldbank.org/knowledgebase/topics/19373-data-compilation-methodology',
       title: 'View all articles in Data Compilation Methodology',
       innerHTML: 'Data Compilation Methodology' },
     { href: 'https://datahelpdesk.worldbank.org/knowledgebase/topics/19285-data-not-available',
       title: 'View all articles in Data Not Available',
       innerHTML: 'Data Not Available' },
     { href: 'https://datahelpdesk.worldbank.org/knowledgebase/topics/19282-data-updates',
       title: 'View all articles in Data Updates',
       innerHTML: 'Data Updates' },
     { href: 'https://datahelpdesk.worldbank.org/knowledgebase/topics/19283-databank',
       title: 'View all articles in DataBank',
       innerHTML: 'DataBank' },
     { href: 'https://datahelpdesk.worldbank.org/knowledgebase/topics/125589-developer-information',
       title: 'View all articles in Developer Information',
       innerHTML: 'Developer Information' },
     { href: 'https://datahelpdesk.worldbank.org/knowledgebase/topics/19287-external-debt',
       title: 'View all articles in External Debt',
       innerHTML: 'External Debt' },
     { href: 'https://datahelpdesk.worldbank.org/knowledgebase/topics/20192-finance-lending',
       title: 'View all articles in Finance/Lending',
       innerHTML: 'Finance/Lending' },
     { href: 'https://datahelpdesk.worldbank.org/knowledgebase/topics/19377-foreign-direct-investment-fdi',
       title: 'View all articles in Foreign Direct Investment (FDI)',
       innerHTML: 'Foreign Direct Investment (FDI)' },
     { href: 'https://datahelpdesk.worldbank.org/knowledgebase/topics/19375-gross-domestic-product-gdp-gross-national-income',
       title: 'View all articles in Gross Domestic Product (GDP)/Gross National Income (GNI)',
       innerHTML: 'Gross Domestic Product (GDP)/Gross National Income (GNI)' },
     { href: 'https://datahelpdesk.worldbank.org/knowledgebase/topics/71785-icp-ppps',
       title: 'View all articles in ICP/PPPs',
       innerHTML: 'ICP/PPPs' },
     { href: 'https://datahelpdesk.worldbank.org/knowledgebase/topics/19292-international-comparison-program-icp',
       title: 'View all articles in International Comparison Program (ICP)',
       innerHTML: 'International Comparison Program (ICP)' },
     { href: 'https://datahelpdesk.worldbank.org/knowledgebase/topics/38788-microdata',
       title: 'View all articles in Microdata',
       innerHTML: 'Microdata' },
     { href: 'https://datahelpdesk.worldbank.org/knowledgebase/topics/124557-open-data-training',
       title: 'View all articles in Open Data Training ',
       innerHTML: 'Open Data Training ' },
     { href: 'https://datahelpdesk.worldbank.org/knowledgebase/topics/19304-other',
       title: 'View all articles in Other',
       innerHTML: 'Other' },
     { href: 'https://datahelpdesk.worldbank.org/knowledgebase/topics/21164-poverty-data',
       title: 'View all articles in Poverty Data',
       innerHTML: 'Poverty Data' },
     { href: 'https://datahelpdesk.worldbank.org/knowledgebase/topics/19378-private-sector-ifc',
       title: 'View all articles in Private Sector (IFC)',
       innerHTML: 'Private Sector (IFC)' },
     { href: 'https://datahelpdesk.worldbank.org/knowledgebase/topics/19358-quarterly-external-debt-statistics-qeds',
       title: 'View all articles in Quarterly External Debt Statistics (QEDS)',
       innerHTML: 'Quarterly External Debt Statistics (QEDS)' },
     { href: 'https://datahelpdesk.worldbank.org/knowledgebase/topics/49089-quarterly-public-sector-debt',
       title: 'View all articles in Quarterly Public Sector Debt',
       innerHTML: 'Quarterly Public Sector Debt' },
     { href: 'https://datahelpdesk.worldbank.org/knowledgebase/topics/118461-subnational-data',
       title: 'View all articles in Subnational Data',
       innerHTML: 'Subnational Data' },
     { href: 'https://datahelpdesk.worldbank.org/knowledgebase/topics/19286-world-development-indicators-wdi',
       title: 'View all articles in World Development Indicators (WDI)',
       innerHTML: 'World Development Indicators (WDI)' },
     { href: 'https://datahelpdesk.worldbank.org/knowledgebase/topics/19303-world-development-report-wdr',
       title: 'View all articles in World Development Report (WDR)',
       innerHTML: 'World Development Report (WDR)' },
     { href: 'https://datahelpdesk.worldbank.org/knowledgebase/articles/all',
       innerHTML: 'All articles' },
     { class: 'uvLink-home',
       href: 'http://data.worldbank.org/',
       innerHTML: 'World Bank Data' },
     { href: 'http://data.worldbank.org/', innerHTML: 'Data' },
     { href: 'https://datahelpdesk.worldbank.org/',
       innerHTML: 'Data Help Desk' },
     { href: 'http://www.worldbank.org/civilsociety',
       innerHTML: 'Civil Society' },
     { href: 'http://consultations.worldbank.org/',
       innerHTML: 'Consultations' },
     { href: 'https://clientconnection.worldbank.org/servlet/main?menuPK=234032&amp;pagePK=232663&amp;piPK=234033',
       innerHTML: '\n                                Government' },
     { href: 'https://clientconnection.worldbank.org/servlet/main?menuPK=234032&amp;pagePK=232663&amp;piPK=234033',
       innerHTML: '\n                                Client Connection' },
     { href: 'http://go.worldbank.org/NOW8S4MAB0',
       innerHTML: 'Parliamentarians' },
     { href: 'http://go.worldbank.org/TRCDVYJ440',
       innerHTML: 'Access to Information' },
     { href: 'http://treasury.worldbank.org/bdm/htm/index.html',
       innerHTML: 'Financing &amp; Risk\n                                Management' },
     { href: 'http://web.worldbank.org/WBSITE/EXTERNAL/OPPORTUNITIES/EXTCORPPROCUREMENT/0,,menuPK:64147159~pagePK:64147234~piPK:64147236~theSitePK:438017,00.html',
       innerHTML: '\n                                Businesses' },
     { href: 'http://go.worldbank.org/6PC0FICAE0',
       innerHTML: 'Corporate Procurement' },
     { href: 'http://go.worldbank.org/FAOKR3OTW0',
       innerHTML: 'Operational Procurement' },
     { href: 'http://treasury.worldbank.org/cmd/htm/index.html',
       innerHTML: 'Investors' },
     { href: 'http://treasury.worldbank.org/cmd/htm/index.html',
       innerHTML: 'World Bank Bonds' },
     { href: 'http://web.worldbank.org/WBSITE/EXTERNAL/EXTJOBSNEW/0,,pagePK:8454306~theSitePK:8453353,00.html',
       innerHTML: '\n                                Job Seekers' },
     { href: 'http://web.worldbank.org/WBSITE/EXTERNAL/NEWS/0,,pagePK:34382~piPK:34439~theSitePK:4607,00.html',
       innerHTML: '\n                                Journalists' },
     { href: 'http://youthink.worldbank.org/',
       innerHTML: 'Students' },
     { href: 'http://www.worldbank.org/en/about',
       innerHTML: 'ABOUT' },
     { href: 'http://www.worldbank.org/en/about/history',
       innerHTML: 'History' },
     { href: 'http://www.worldbank.org/en/about/leadership',
       innerHTML: 'Leadership' },
     { href: 'http://web.worldbank.org/WBSITE/EXTERNAL/EXTABOUTUS/0,,contentMDK:20437854~menuPK:1697253~pagePK:51123644~piPK:329829~theSitePK:29708,00.html',
       innerHTML: '\n                                            Public Outreach' },
     { href: 'http://www.worldbank.org/en/events',
       innerHTML: 'Events' },
     { href: 'http://www.worldbank.org/jobs', innerHTML: 'Jobs' },
     { href: 'http://www.worldbank.org/annualreport',
       innerHTML: 'Annual Reports' },
     { href: 'http://data.worldbank.org/', innerHTML: 'DATA' },
     { href: 'http://search.worldbank.org/data',
       innerHTML: 'Search Data' },
     { href: 'http://databank.worldbank.org/ddp/home.do?Step=12&amp;id=4&amp;CNO=2',
       innerHTML: 'DataBank' },
     { href: 'http://data.worldbank.org/data-catalog',
       innerHTML: 'Catalog' },
     { href: 'http://data.worldbank.org/products',
       innerHTML: 'Data Publications &amp; Products' },
     { href: 'http://data.worldbank.org/developers',
       innerHTML: 'APIs for Developers' },
     { href: 'http://econ.worldbank.org/WBSITE/EXTERNAL/EXTDEC/0,,menuPK:476823~pagePK:64165236~piPK:64165141~theSitePK:469372,00.html',
       innerHTML: '\n                                            RESEARCH' },
     { href: 'http://search.worldbank.org/research',
       innerHTML: 'Search Research' },
     { href: 'http://econ.worldbank.org/datasets',
       innerHTML: 'Tools &amp; Tables' },
     { href: 'http://www.worldbank.org/reference/',
       innerHTML: 'Research Publications &amp; Products' },
     { href: 'http://wbi.worldbank.org/wbi/', innerHTML: 'LEARNING' },
     { href: 'http://gdln.org/',
       innerHTML: 'Global Development Learning Network' },
     { href: 'http://web.worldbank.org/WBSITE/EXTERNAL/TOPICS/EXTCDRC/0,,menuPK:64169181~pagePK:64169192~piPK:64169180~theSitePK:489952,00.html',
       innerHTML: '\n                                            Capacity Development Resource Center' },
     { href: 'http://web.worldbank.org/WBSITE/EXTERNAL/DATASTATISTICS/SCBEXTERNAL/0,,contentMDK:20100922~menuPK:982273~pagePK:229544~piPK:229605~theSitePK:239427,00.html',
       innerHTML: '\n                                            Statistical Capacity Building' },
     { href: 'http://web.worldbank.org/WBSITE/EXTERNAL/WBI/EXTWBISFP/0,,menuPK:551559~pagePK:64168427~piPK:64168435~theSitePK:551553,00.html',
       innerHTML: '\n                                            Scholarships &amp; Fellowships' },
     { href: 'http://www.worldbank.org/en/news', innerHTML: 'NEWS' },
     { href: 'http://www.worldbank.org/en/news/all',
       innerHTML: 'Search for News' },
     { href: 'http://blogs.worldbank.org/', innerHTML: 'Blogs' },
     { href: 'http://www.worldbank.org/en/news/multimedia',
       innerHTML: 'Multimedia' },
     { href: 'http://media.worldbank.org/',
       innerHTML: 'Media Briefing Center' },
     { href: 'http://www.worldbank.org/en/about/contacts',
       innerHTML: 'Media Contacts' },
     { href: 'http://web.worldbank.org/WBSITE/EXTERNAL/PROJECTS/0,,menuPK:115635~pagePK:64020917~piPK:64021009~theSitePK:40941,00.html',
       innerHTML: '\n                                            PROJECTS &amp; OPERATIONS ' },
     { href: 'http://search.worldbank.org/projects',
       innerHTML: 'Search Projects' },
     { href: 'http://web.worldbank.org/WBSITE/EXTERNAL/PROJECTS/0,,contentMDK:20120721~menuPK:232467~pagePK:41367~piPK:51533~theSitePK:40941,00.html',
       innerHTML: '\n                                            Products &amp; Services' },
     { href: 'http://web.worldbank.org/WBSITE/EXTERNAL/PROJECTS/0,,menuPK:64383817~pagePK:64387457~piPK:64387543~theSitePK:40941,00.html',
       innerHTML: '\n                                            Country Lending' },
     { href: 'http://www.worldbank.org/ieg/',
       innerHTML: 'Project Evaluations' },
     { href: 'http://www.worldbank.org/results/',
       innerHTML: 'Results' },
     { href: 'http://www.worldbank.org/reference/',
       innerHTML: 'PUBLICATIONS' },
     { href: 'http://publications.worldbank.org/',
       innerHTML: 'Bookstore' },
     { href: 'http://www-wds.worldbank.org/WBSITE/EXTERNAL/EXTWDS/0,,detailPagemenuPK:64187510~menuPK:64187513~pagePK:64187848~piPK:64187934~searchPagemenuPK:64187283~siteName:WDS~theSitePK:523679,00.html',
       innerHTML: '\n                                            Documents &amp; Reports' },
     { href: 'http://web.worldbank.org/WBSITE/EXTERNAL/EXTABOUTUS/EXTARCHIVES/0,,pagePK:38167~theSitePK:29506,00.html',
       innerHTML: '\n                                            Archives' },
     { href: 'http://jolis.worldbankimflib.org/external.htm',
       innerHTML: 'Libraries' },
     { href: 'http://www.worldbank.org/en/country',
       innerHTML: 'COUNTRIES ' },
     { href: 'http://www.worldbank.org/en/topic',
       innerHTML: 'TOPICS' },
     { title: 'International Bank for Reconstruction and Development',
       href: 'http://www.worldbank.org/ibrd',
       innerHTML: '\n                            IBRD' },
     { title: 'International Development Association',
       href: 'http://www.worldbank.org/ida',
       innerHTML: '\n                                IDA' },
     { title: 'International Finance Corporation',
       href: 'http://www.ifc.org/',
       innerHTML: 'IFC' },
     { title: 'Multilateral Investment Guarantee Agency',
       href: 'http://www.miga.org/',
       innerHTML: 'MIGA' },
     { title: 'International Centre for Settlement of Investment Disputes',
       href: 'http://icsid.worldbank.org/',
       innerHTML: '\n                            ICSID' },
     { href: 'http://www.worldbank.org/legalinfo',
       innerHTML: 'Legal' },
     { href: 'http://go.worldbank.org/TRCDVYJ440',
       innerHTML: '\n                            Access to Information' },
     { href: 'http://www.worldbank.org/jobs', innerHTML: 'Jobs' },
     { href: 'http://www.worldbank.org/sitemap',
       innerHTML: 'Site Map' },
     { href: 'http://www.worldbank.org/contacts',
       innerHTML: '\n                                    Contact' },
     { href: 'http://www.worldbank.org/',
       innerHTML: '©\n\n                            The World Bank Group, All Rights Reserved.' },
     { href: 'http://web.worldbank.org/WBSITE/EXTERNAL/EXTABOUTUS/ORGANIZATION/ORGUNITS/EXTDOII/0,,contentMDK:20659616~menuPK:1702202~pagePK:64168445~piPK:64168309~theSitePK:588921,00.html',
       innerHTML: '\n                            ' },
     { class: 'url',
       href: '${user.uservoice_url}',
       innerHTML: '\n          ' },
     { href: '/remember_me',
       title: 'Click this link to stay signed in on this computer even after your browser is closed.',
       innerHTML: 'Stay signed in' },
     { class: 'url',
       href: '${user.uservoice_url}',
       innerHTML: 'Settings' },
     { href: 'https://datahelpdesk.worldbank.org/admin',
       innerHTML: 'Admin Console' },
     { href: '/logout', innerHTML: 'Sign out' },
     { href: '${url}', innerHTML: '${name}' },
     { href: '${url}', innerHTML: '${name}' },
     { href: '${url}',
       title: 'View all ideas in ${name}',
       innerHTML: '${name}' },
     { href: 'https://community.uservoice.com/blog/uservoice-security-incident-notification/',
       target: '_blank',
       innerHTML: 'security incident' },
     { id: 'fancybox-close' },
     { href: 'javascript:;', id: 'fancybox-left' },
     { href: 'javascript:;', id: 'fancybox-right' } ],
  form: 
   [ { method: 'get',
       action: 'http://search.worldbank.org/data',
       'accept-charset': 'UTF-8',
       class: 'clear-block',
       innerHTML: '\n                    ' },
     { novalidate: ' class=', innerHTML: '\n      \n' },
     { action: 'https://datahelpdesk.worldbank.org/api/v1/search?weight_minimum=40&amp;lang=en',
       innerHTML: '\n      ' } ],
  input: 
   [ { id: 'in-search-keyword',
       type: 'text',
       size: '15',
       name: 'qterm',
       class: 'search-text',
       placeholder: 'Search',
       innerHTML: '\n\t\t\t\t\t' },
     { type: 'hidden',
       name: 'language',
       value: 'EN',
       innerHTML: '\n\t\t\t\t\t' },
     { type: 'submit',
       class: 'search-btn',
       name: 'op',
       value: '',
       innerHTML: '\n\t\t\t\t\t' },
     { class: 'uvFieldText',
       type: 'text',
       name: 'display_name',
       id: 'display_name_817',
       title: 'Your name',
       innerHTML: '\n        ' },
     { class: 'uvFieldText',
       type: 'email',
       name: 'email',
       id: 'email_817',
       value: ' title=',
       innerHTML: '\n        ' },
     { class: 'uvFieldPassword',
       type: 'password',
       name: 'password',
       id: 'password_817',
       title: 'UserVoice password',
       innerHTML: '\n          ' },
     { type: 'checkbox',
       name: 'tos-checkbox',
       title: 'Terms of Service',
       innerHTML: '\n           I agree to the ' },
     { type: 'hidden',
       name: 'uninitialized',
       value: 'true',
       innerHTML: '\n' },
     { class: 'uvFieldText',
       name: 'query',
       type: 'text',
       id: 'combined_search_sidebar',
       innerHTML: '\n\n          ' } ],
  ul: 
   [ { innerHTML: '\n                        ' },
     { class: '', innerHTML: '\n                    ' },
     { class: 'links primary-links clear-block', innerHTML: '\n' },
     { class: 'links secondary-links clear-block',
       innerHTML: '\n                            ' },
     { class: 'uvFieldEtc uvFieldEtc-providers uvFieldEtc-third_party' },
     { class: 'button-states-language', innerHTML: '\n    ' },
     { class: 'uvList uvList-searchResults',
       innerHTML: '\n              {{each(i, article) articles}}\n                ' },
     { class: 'uvList uvList-searchResults',
       innerHTML: '\n              {{each(i, idea) suggestions}}\n                ' },
     { class: 'uvNavList', innerHTML: '\n      ' },
     { class: 'uvNavList', innerHTML: '\n\n        ' },
     { class: 'uvList uvList-forums',
       'data-tmpl': 'sidebarForumsTmpl',
       innerHTML: '\n              ' },
     { class: 'uvList uvList-topics',
       innerHTML: '\n                                        ' },
     { class: 'misc-links-list',
       innerHTML: '\n                        ' } ],
  li: 
   [ { class: '' },
     { class: '' },
     { class: '' },
     { class: '' },
     { class: '' },
     { class: 'cn' },
     { class: '' },
     { class: '' },
     { class: 'active' },
     { class: '' },
     { class: '' },
     { class: '' },
     { class: '' },
     { class: '' },
     { class: '' },
     { class: '' },
     { class: 'country first' },
     { class: 'topic' },
     { class: 'indicator' },
     { class: 'data-catalog' },
     { class: 'http:--microdata-worldbank-org' },
     { class: 'http:--blogs-worldbank-org-opendata last' },
     { class: 'news first' },
     { class: 'pages-8' },
     { class: 'pages-9' },
     { class: 'pages-7 last' },
     { 'data-provider': 'facebook' },
     { 'data-provider': 'google' },
     { class: 'sign-in-button-text', innerHTML: 'Sign in' },
     { class: 'sign-up-button-text', innerHTML: 'Sign up' },
     { class: 'uvListItem uvListItem-article' },
     { class: 'uvListItem uvListItem-article' },
     { class: 'uvListItem uvListItem-article' },
     { class: 'uvListItem uvListItem-article' },
     { class: 'uvListItem uvListItem-article' },
     { class: 'uvListItem uvListItem-article' },
     { class: 'uvListItem uvListItem-article' },
     { class: 'uvListItem uvListItem-article' },
     { class: 'uvListItem uvListItem-article' },
     { class: 'uvListItem uvListItem-article' },
     { class: 'uvListItem uvListItem-article' },
     { class: 'uvListItem uvListItem-article' },
     { class: 'uvListItem uvListItem-article uvListItem-selected' },
     { class: 'uvListItem uvListItem-article' },
     { class: 'uvListItem uvListItem-article' },
     { class: 'uvListItem uvListItem-article' },
     { class: 'uvListItem uvListItem-searchResult',
       'data-search-weight': '${article.weight}',
       innerHTML: '\n                  ' },
     { class: 'uvListItem uvListItem-searchResult',
       'data-search-weight': '${idea.weight}',
       innerHTML: '\n                {{if idea.status && idea.status.name}}\n                  ' },
     { class: 'uvNavListItem uvNavListItem-search uvSearch-results-container',
       style: 'display: none;',
       innerHTML: '\n        ' },
     { class: 'uvNavListItem uvNavListItem-contactus',
       innerHTML: '\n          ' },
     { class: 'uvNavListItem uvNavListItem-feedback',
       innerHTML: '\n          ' },
     { class: 'uvListItem uvListItem-forum uvListItem-forum-203367',
       innerHTML: '\n                ' },
     { class: 'uvListItem uvListItem-forum uvListItem-forum-162856',
       innerHTML: '\n                ' },
     { class: 'uvListItem uvListItem-forum uvListItem-forum-170263',
       innerHTML: '\n                ' },
     { class: 'uvNavListItem uvNavListItem-helpdesk',
       innerHTML: '\n        ' },
     { class: 'uvListItem uvListItem-topic uvListItem-topic-19280',
       innerHTML: '\n                    ' },
     { class: 'uvListItem uvListItem-topic uvListItem-topic-19371',
       innerHTML: '\n                    ' },
     { class: 'uvListItem uvListItem-topic uvListItem-topic-19373',
       innerHTML: '\n                    ' },
     { class: 'uvListItem uvListItem-topic uvListItem-topic-19285',
       innerHTML: '\n                    ' },
     { class: 'uvListItem uvListItem-topic uvListItem-topic-19282',
       innerHTML: '\n                    ' },
     { class: 'uvListItem uvListItem-topic uvListItem-topic-19283',
       innerHTML: '\n                    ' },
     { class: 'uvListItem uvListItem-topic uvListItem-topic-125589 uvListItem-selected',
       innerHTML: '\n                    ' },
     { class: 'uvListItem uvListItem-topic uvListItem-topic-19287',
       innerHTML: '\n                    ' },
     { class: 'uvListItem uvListItem-topic uvListItem-topic-20192',
       innerHTML: '\n                    ' },
     { class: 'uvListItem uvListItem-topic uvListItem-topic-19377',
       innerHTML: '\n                    ' },
     { class: 'uvListItem uvListItem-topic uvListItem-topic-19375',
       innerHTML: '\n                    ' },
     { class: 'uvListItem uvListItem-topic uvListItem-topic-71785',
       innerHTML: '\n                    ' },
     { class: 'uvListItem uvListItem-topic uvListItem-topic-19292',
       innerHTML: '\n                    ' },
     { class: 'uvListItem uvListItem-topic uvListItem-topic-38788',
       innerHTML: '\n                    ' },
     { class: 'uvListItem uvListItem-topic uvListItem-topic-124557',
       innerHTML: '\n                    ' },
     { class: 'uvListItem uvListItem-topic uvListItem-topic-19304',
       innerHTML: '\n                    ' },
     { class: 'uvListItem uvListItem-topic uvListItem-topic-21164',
       innerHTML: '\n                    ' },
     { class: 'uvListItem uvListItem-topic uvListItem-topic-19378',
       innerHTML: '\n                    ' },
     { class: 'uvListItem uvListItem-topic uvListItem-topic-19358',
       innerHTML: '\n                    ' },
     { class: 'uvListItem uvListItem-topic uvListItem-topic-49089',
       innerHTML: '\n                    ' },
     { class: 'uvListItem uvListItem-topic uvListItem-topic-118461',
       innerHTML: '\n                    ' },
     { class: 'uvListItem uvListItem-topic uvListItem-topic-19286',
       innerHTML: '\n                    ' },
     { class: 'uvListItem uvListItem-topic uvListItem-topic-19303',
       innerHTML: '\n                    ' },
     { class: 'uvListItem uvListItem-topic uvListItem-topic-all ',
       innerHTML: '\n                ' },
     { class: 'uvNavListItem uvNavListItem-home',
       innerHTML: '\n        ' },
     { class: 'first', innerHTML: 'You Are here' },
     { class: 'divider', innerHTML: '&gt;' },
     { class: 'divider', innerHTML: '&gt;' },
     { class: 'header', innerHTML: 'resources' },
     { class: 'subheader' },
     { class: 'subheader' },
     { class: 'subheader' },
     { class: 'subheader' },
     { class: 'subheader' },
     { class: 'subheader' },
     { class: 'subheader' },
     { class: 'subheader' },
     { class: 'fullwidth margin-bottom20',
       innerHTML: '\n                                ' },
     { class: 'header' },
     { class: 'header' },
     { class: 'header' },
     { class: 'header' },
     { class: 'fullwidth margin-bottom10',
       innerHTML: '\n                                ' },
     { class: 'header' },
     { class: 'header' },
     { class: 'header' },
     { class: 'header' },
     { class: 'header' },
     { class: 'links' },
     { class: 'copyright' },
     { class: 'uvListItem{{if current_forum_id==id}} uvListItem-selected{{/if}} uvListItem-forum-${id}',
       innerHTML: '\n      ' },
     { class: 'uvListItem{{if current_forum_id==id}} uvListItem-selected{{/if}} uvListItem-forum-${id}',
       innerHTML: '\n      ' },
     { class: 'uvListItem uvListItem-forum{{if current_forum_id==id}} uvListItem-selected{{/if}} uvListItem-forum-${id}',
       innerHTML: '\n      ' } ],
  article: [ { innerHTML: '\n        ' } ],
  header: 
   [ { class: 'uvPageHeader', innerHTML: '\n          ' },
     { class: 'uvModuleHeader hide',
       style: 'position: absolute;',
       innerHTML: '\n    ' } ],
  h1: 
   [ { class: 'uvPageTitle uvCustomPrimary-color',
       innerHTML: 'Data Catalog API' },
     { class: 'uvModuleSectionHeader uvCustomPrimary-color' },
     { class: 'uvCustomPrimary-color hidden',
       innerHTML: 'Your password has been reset' } ],
  section: 
   [ { class: 'uvFaq typeset', innerHTML: '\n            ' },
     { class: 'uvModuleSection uvModuleSection-userbox uvModuleSection-signin',
       innerHTML: '\n      ' },
     { class: 'uvModuleSection uvModuleSection-list',
       innerHTML: '\n          ' },
     { class: 'uvModuleSection uvModuleSection-search',
       innerHTML: '\n    ' },
     { class: 'uvModuleSection', innerHTML: '\n    ' },
     { class: 'uvModuleSection uvModuleSection-userbox uvModuleSection-signout',
       innerHTML: '\n      ' } ],
  h3: [ { innerHTML: 'Sample API Response' } ],
  p: 
   [ { innerHTML: 'For any valid request, the API will return one or more objects or rows, each representing a dataset from the data catalog. They are uniquely identified by the data catalog id attribute.' },
     { class: 'uvStyle-signin',
       innerHTML: 'Thank you for visiting the World Bank\'s Data Help Desk. Please review the ' },
     { class: 'last' },
     { class: 'uvSearch-more-results' },
     { class: 'uvSearch-more-results' },
     { class: 'uvNoResults', innerHTML: 'No results.' },
     { class: 'uvStyle-meta',
       innerHTML: '\n      We\'ve just sent you an email to ' } ],
  code: [ { innerHTML: '{"page":1,"pages":13,"per_page":"10","total":130,"datacatalog":[{"id":"1","metatype":[{"id":"name","value":"World Development Indicators"},{"id":"acronym","value":"WDI"},{"id":"description","value":"The primary World Bank collection of development indicators, compiled from officially-recognized international sources. It presents the most current and accurate global development data available, and includes national, regional and global estimates."},{"id":"url","value":"http://databank.worldbank.org/ddp/home.do?Step=12&amp;id=4&amp;CNO=2"}' } ],
  b: [ { innerHTML: 'JSON' } ],
  br: [ { innerHTML: '\n                            ' } ],
  footer: [ { class: 'uvFaqFooter', innerHTML: '\n          ' } ],
  span: 
   [ { class: 'uvFaqAction uvFaqAction-helpful',
       innerHTML: '\n            ' },
     { class: 'uvStyle-button-label',
       'data-washelpful': 'Great! Glad we could help.',
       innerHTML: 'This article was helpful' },
     { style: 'display: none;', innerHTML: '(thinking…)' },
     { class: 'uvFieldEtc-thinking', innerHTML: '(thinking…)' },
     { class: 'uvStyle-separator', innerHTML: '&nbsp;·&nbsp;' },
     { class: 'uvFaqAction uvFaqAction-flag',
       innerHTML: '\n            ' },
     { class: 'uvStyle-separator uvAdminOnly uvAdminOnly-inline',
       innerHTML: '&nbsp;·&nbsp;' },
     { class: 'uvFieldPlaceholder', innerHTML: 'Your name' },
     { class: 'uvFieldPlaceholder', innerHTML: 'Your email address' },
     { class: 'uvFieldEtcLabel', innerHTML: 'or sign in with' },
     { class: 'uvFieldPlaceholder',
       innerHTML: '\n      Signed in as ' },
     { class: 'logged_in_as' },
     { class: 'uvModuleTriggerTwirl' },
     { class: 'uvFieldPlaceholder', innerHTML: 'Search' },
     { class: 'uvFieldButtonImage-sidebar', innerHTML: 'Search' },
     { class: 'uvStyle-count', innerHTML: '1' },
     { class: 'uvStyle-count-label', innerHTML: ' idea' },
     { class: 'uvStyle-count', innerHTML: '5' },
     { class: 'uvStyle-count-label', innerHTML: ' ideas' },
     { class: 'uvStyle-count', innerHTML: '2' },
     { class: 'uvStyle-count-label', innerHTML: ' ideas' },
     { class: 'uvStyle-count', innerHTML: '7' },
     { class: 'uvStyle-count-label', innerHTML: ' articles' },
     { class: 'uvStyle-count', innerHTML: '4' },
     { class: 'uvStyle-count-label', innerHTML: ' articles' },
     { class: 'uvStyle-count', innerHTML: '10' },
     { class: 'uvStyle-count-label', innerHTML: ' articles' },
     { class: 'uvStyle-count', innerHTML: '7' },
     { class: 'uvStyle-count-label', innerHTML: ' articles' },
     { class: 'uvStyle-count', innerHTML: '3' },
     { class: 'uvStyle-count-label', innerHTML: ' articles' },
     { class: 'uvStyle-count', innerHTML: '13' },
     { class: 'uvStyle-count-label', innerHTML: ' articles' },
     { class: 'uvStyle-count', innerHTML: '16' },
     { class: 'uvStyle-count-label', innerHTML: ' articles' },
     { class: 'uvStyle-count', innerHTML: '5' },
     { class: 'uvStyle-count-label', innerHTML: ' articles' },
     { class: 'uvStyle-count', innerHTML: '1' },
     { class: 'uvStyle-count-label', innerHTML: ' article' },
     { class: 'uvStyle-count', innerHTML: '2' },
     { class: 'uvStyle-count-label', innerHTML: ' articles' },
     { class: 'uvStyle-count', innerHTML: '4' },
     { class: 'uvStyle-count-label', innerHTML: ' articles' },
     { class: 'uvStyle-count', innerHTML: '1' },
     { class: 'uvStyle-count-label', innerHTML: ' article' },
     { class: 'uvStyle-count', innerHTML: '2' },
     { class: 'uvStyle-count-label', innerHTML: ' articles' },
     { class: 'uvStyle-count', innerHTML: '15' },
     { class: 'uvStyle-count-label', innerHTML: ' articles' },
     { class: 'uvStyle-count', innerHTML: '1' },
     { class: 'uvStyle-count-label', innerHTML: ' article' },
     { class: 'uvStyle-count', innerHTML: '4' },
     { class: 'uvStyle-count-label', innerHTML: ' articles' },
     { class: 'uvStyle-count', innerHTML: '11' },
     { class: 'uvStyle-count-label', innerHTML: ' articles' },
     { class: 'uvStyle-count', innerHTML: '1' },
     { class: 'uvStyle-count-label', innerHTML: ' article' },
     { class: 'uvStyle-count', innerHTML: '6' },
     { class: 'uvStyle-count-label', innerHTML: ' articles' },
     { class: 'uvStyle-count', innerHTML: '2' },
     { class: 'uvStyle-count-label', innerHTML: ' articles' },
     { class: 'uvStyle-count', innerHTML: '6' },
     { class: 'uvStyle-count-label', innerHTML: ' articles' },
     { class: 'uvStyle-count', innerHTML: '10' },
     { class: 'uvStyle-count-label', innerHTML: ' articles' },
     { class: 'uvStyle-count', innerHTML: '1' },
     { class: 'uvStyle-count-label', innerHTML: ' article' },
     { class: 'wbg-logo',
       title: 'The World Bank Working for a World Free of Poverty',
       innerHTML: '1-202-458-7677' },
     { class: 'uvUserBadge', innerHTML: '\n            ' },
     { class: 'fn', innerHTML: '${user.name}' },
     { class: 'uvRememberMe', innerHTML: '(' },
     { class: 'uvStyle-separator', innerHTML: '&middot;' },
     { class: 'uvStyle-separator', innerHTML: '&middot;' },
     { class: 'uvIcon-private-16', innerHTML: '(private)' },
     { class: 'uvStyle-count-label', innerHTML: 'ideas' },
     { class: 'uvIcon-private-10', innerHTML: '(private)' },
     { class: 'uvIcon-private-10', innerHTML: '(private)' },
     { class: 'uvStyle-count', innerHTML: '${idea_count} ' },
     { class: 'uvStyle-count-label', innerHTML: 'ideas' },
     { class: 'uvPasswordReset-email' },
     { class: 'fancy-ico', id: 'fancybox-left-ico' },
     { class: 'fancy-ico', id: 'fancybox-right-ico' } ],
  button: 
   [ { href: '/api/v1/articles/902049/useful',
       class: 'uvStyle-button uvStyle-button-helpful',
       innerHTML: '\n              ' },
     { class: 'uvFlagObject uvUserOnly uvUserOnly-inline uvStyle-link',
       'data-success': 'Flagged',
       'data-url': '/api/v1/faqs/902049-data-catalog-api/flags?code=inaccurate',
       type: 'button',
       innerHTML: 'Flag this article as inaccurate…' },
     { class: 'uvFieldEtc-submit-button uvStyle-button',
       innerHTML: 'Sign in' },
     { class: 'uvFieldEtc-cancel-page', innerHTML: 'Cancel' },
     { class: 'uvFieldButton uvStyle-button', type: 'submit' },
     { type: 'reset',
       class: 'uvFieldEtc uvFieldEtc-reset',
       innerHTML: 'Reset' },
     { type: 'button',
       class: 'uvLink-contactus uvStyle-link uvCustomLink-color',
       innerHTML: 'Contact support' },
     { class: 'uvPasswordReset-dialog-close-button close-button',
       onclick: 'event.preventDefault(); UV.jQuery(&#39;.uvPasswordReset-overlay&#39;).hide();' },
     { class: 'uvStyle-button',
       onclick: 'event.preventDefault(); UV.jQuery(&#39;.uvPasswordReset-overlay&#39;).hide();',
       innerHTML: 'Continue' } ],
  img: 
   [ { alt: 'smiley face',
       src: '//assets1.uvcdn.com/pkg/clients/_icons/icon.smile.32px-7404a3b9fa862ace06fc90f307720ec8.png',
       width: '32',
       innerHTML: '-->\n              ' },
     { class: 'favicon',
       src: './Data Catalog API – World Bank Data Help Desk_files/facebook-8b92ce8bf5e8258f342c1990afd055fc.png',
       alt: 'facebook' },
     { class: 'favicon',
       src: './Data Catalog API – World Bank Data Help Desk_files/google-3c303af007c64a872d4822fbac21253e.png',
       alt: 'google' },
     { alt: 'Password icon',
       class: 'password',
       src: './Data Catalog API – World Bank Data Help Desk_files/password-d904f06a67a7b29d489489d3a35f548b.png',
       innerHTML: '\n        ' },
     { alt: ' class=',
       'uvUserBadgePhotophoto"src': '${user.avatar_url}',
       width: '40',
       innerHTML: '\n          ' },
     { name: 's_i_wbnispwbdhd',
       height: '1',
       width: '1',
       border: '0',
       alt: ' src=',
       innerHTML: '\n    ' } ],
  fieldset: 
   [ { class: 'uvSignin uvSignin-default uvSignin-custom-tos uvFieldset',
       'data-options': '{&quot;subclass&quot;:&quot;StandaloneSignin&quot;}',
       'aria-live': 'polite',
       'aria-relevant': 'additions removals',
       'data-subclass': 'StandaloneSignin',
       innerHTML: '\n  ' } ],
  legend: [ { class: 'uvSigninLegend', innerHTML: 'Sign in' } ],
  label: 
   [ { class: 'uvFieldInner',
       for: 'display_name_817',
       innerHTML: '\n          ' },
     { class: 'uvFieldInner',
       for: 'email_817',
       innerHTML: '\n          ' },
     { class: 'uvFieldInner',
       for: 'password_817',
       innerHTML: '\n            ' },
     { class: 'uvFieldInner', innerHTML: '\n           ' },
     { class: 'uvFieldInner',
       for: 'combined_search_sidebar',
       innerHTML: '\n        ' } ],
  ol: 
   [ { class: 'uvList uvList-articles',
       innerHTML: '\n              ' } ],
  h4: 
   [ { class: 'uvNavListItemSubtitle',
       innerHTML: '${total_articles} {{if total_articles > 1}}articles{{else}}article{{/if}}' },
     { class: 'uvNavListItemSubtitle',
       innerHTML: '${total_suggestions} {{if total_suggestions > 1}}ideas{{else}}idea{{/if}}' },
     { class: 'uvListItemHeader', innerHTML: '\n        ' },
     { class: 'uvListItemHeader', innerHTML: '\n        ' } ],
  em: 
   [ { class: 'uvStyle-status uvStyle-status-${idea.status.key}',
       '\ntitle': 'This idea is ${idea.status.name} ${$.tmplHelpers.toLocalDate(idea.updated_at, - updated %date%)}',
       innerHTML: '${idea.status.name}' } ],
  h2: 
   [ { class: 'uvNavListItemTitle uvSearch-results-title uvCustomPrimary-color',
       innerHTML: '\n          Searching…\n        ' },
     { class: 'uvNavListItemTitle', innerHTML: '\n              ' },
     { class: 'uvNavListItemTitle', innerHTML: '\n            ' },
     { class: 'uvNavListItemTitle', innerHTML: '\n            ' },
     { class: 'uvNavListItemTitle', innerHTML: '\n          ' } ],
  strong: [ { innerHTML: 'Fraud &amp; Corruption Hotline' } ],
  'd.length;c++){mpq[d[c]]=e(d[c])}})();\n</script': [] }
